apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: coturn
  labels:
    app: coturn
    tier: infrastructure
spec:
  serviceName: coturn
  replicas: 1
  selector:
    matchLabels:
      app: coturn
  template:
    metadata:
      labels:
        app: coturn
        tier: infrastructure
    spec:
      containers:
        - name: coturn
          image: coturn/coturn:4.6
          args:
            - -c
            - /etc/coturn/turnserver.conf
          ports:
            - containerPort: 3478
              protocol: UDP
              name: stun-udp
            - containerPort: 3478
              protocol: TCP
              name: stun-tcp
            - containerPort: 5349
              protocol: UDP
              name: stuns-udp
            - containerPort: 5349
              protocol: TCP
              name: stuns-tcp
          volumeMounts:
            - name: config
              mountPath: /etc/coturn/turnserver.conf
              subPath: turnserver.conf
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
      volumes:
        - name: config
          configMap:
            name: coturn-config
