# ExternalName service pointing to ElastiCache
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  type: ExternalName
  externalName: ${ELASTICACHE_ENDPOINT}
  ports:
    - port: 6379
