# ExternalName service pointing to RDS
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  type: ExternalName
  externalName: ${RDS_ENDPOINT}
  ports:
    - port: 5432
