apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: board-service
  namespace: argocd
spec:
  project: wealist
  source:
    repoURL: https://github.com/your-org/wealist-project-advanced.git
    targetRevision: main
    path: services/board-service/k8s/overlays/local
  destination:
    server: https://kubernetes.default.svc
    namespace: wealist-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
