# Infrastructure Application (postgres, redis)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wealist-infrastructure
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: wealist
  source:
    repoURL: https://github.com/YOUR_ORG/wealist-project-advanced.git  # TODO: Update
    targetRevision: HEAD
    path: infrastructure/overlays/eks  # Change to 'local' for local env
  destination:
    server: https://kubernetes.default.svc
    namespace: wealist
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
