apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wealist-infrastructure
  namespace: argocd
spec:
  project: wealist
  source:
    repoURL: https://github.com/your-org/wealist-project-advanced.git
    targetRevision: main
    path: infrastructure/overlays/local
  destination:
    server: https://kubernetes.default.svc
    namespace: wealist-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
