# ArgoCD App-of-Apps pattern
# This root application manages all other applications
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wealist-root
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: wealist
  source:
    repoURL: https://github.com/YOUR_ORG/wealist-project-advanced.git  # TODO: Update
    targetRevision: HEAD
    path: argocd/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
