# Redis Secret
# TODO: In production, use External Secrets Operator with Vault
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
type: Opaque
stringData:
  REDIS_PASSWORD: "CHANGE_ME_IN_OVERLAY"
